//! Bedy Proof of Concept declarations crate

mod objects {
    pub mod normalized {
        use bedy_common::Id;

        pub struct Person {
            pub name: String,
            pub city: Id<City>,
        }

        pub struct City {
            // #[bedy(unique)]
            pub name: String,
        }

        // TODO: autogenerated because of #[bedy(unique)]
        #[cfg(feature = "server")]
        mod city_indexes {
            use bedy_server::index::Index;

            impl Index<super::City> for String {}
        }
    }

    pub mod denormalized {
        pub struct PersonDisplay {
            pub name: String,
            pub city: String,
        }
    }
}

mod queries {
    // TODO: generate these automatically?
    mod auto {
        mod person {
            use bedy_common::{Id, Record};
            use bedy_server::{
                extractor::Param,
                query::{Query, QueryMut},
            };

            use crate::objects::normalized::Person;

            fn insert(Param(person): Param<Person>, mut people: QueryMut<Person>) -> Id<Person> {
                people.insert(&person)
            }

            fn find(Param(id): Param<Id<Person>>, people: Query<Person>) -> Option<Person> {
                people.find(id).map(|(_, object)| object)
            }

            fn update(Param(record): Param<Record<Person>>, mut people: QueryMut<Person>) {
                people.update(record);
            }

            fn remove(Param(id): Param<Id<Person>>, mut people: QueryMut<Person>) {
                people.delete(id);
            }
        }

        mod city {
            use bedy_common::Record;
            use bedy_server::{extractor::Param, query::Query};

            use crate::objects::normalized::City;

            fn find_by_name(Param(name): Param<String>, cities: Query<City, String>) -> Option<Record<City>> {
                cities.find(name)
            }
        }
    }

    mod custom {
        mod people {
            use bedy_common::Id;
            use bedy_server::{extractor::Param, query::Query};

            use crate::objects::{
                denormalized::PersonDisplay,
                normalized::{City, Person},
            };

            fn display_people(people: Query<Person>, cities: Query<City>) -> impl Iterator<Item = PersonDisplay> {
                people.iter().map(move |(_id, person)| PersonDisplay {
                    name: person.name,
                    city: cities.find(person.city).expect("foreign key exists").1.name,
                })
            }

            fn people_within(Param(city): Param<Id<City>>, people: Query<Person>) -> impl Iterator<Item = Id<Person>> {
                people.iter().filter_map(move |(id, person)| (person.city == city).then_some(id))
            }
        }
    }
}

// TEMP: generated client example
#[cfg(feature = "client")]
mod client {
    mod bedy_client {
        use derive_getters::Getters;

        use super::{city::CityClient, person::PersonClient};

        #[derive(Getters)]
        pub struct BedyClient {
            person: PersonClient,
            city: CityClient,
        }
    }
    pub use bedy_client::BedyClient;

    mod person {
        use bedy_client::ClientCrud;
        use bedy_common::Id;
        use futures::Stream;

        use crate::objects::{
            denormalized::PersonDisplay,
            normalized::{City, Person},
        };

        pub struct PersonClient {}

        impl ClientCrud<Person> for PersonClient {}

        impl PersonClient {
            // async because we might need to wait for the people and city write locks to be released
            pub async fn display_people(&self) -> impl Stream<Item = PersonDisplay> {
                todo!()
            }

            pub async fn people_within(&self, city: Id<City>) -> impl Stream<Item = Id<Person>> {
                todo!()
            }
        }
    }
    pub use person::PersonClient;

    mod city {
        use bedy_client::ClientCrud;
        use bedy_common::Record;

        use crate::objects::normalized::City;

        pub struct CityClient {}

        impl ClientCrud<City> for CityClient {}

        impl CityClient {
            pub async fn find_by_name(&self, name: &str) -> Option<Record<City>> {
                todo!()
            }
        }
    }
    pub use city::CityClient;
}

mod chained_sketch {
    use bedy_client::ClientCrud;
    use futures::StreamExt;

    use crate::client::*;

    // Back and forth
    async fn remove_people_in(city_name: &str, db: &BedyClient) -> usize {
        let mut removed_count = 0;

        if let Some((city_id, _)) = db.city().find_by_name(city_name).await {
            while let Some(person_id) = db.person().people_within(city_id).await.next().await {
                if db.person().remove(person_id).await.is_some() {
                    removed_count += 1;
                }
            }
        }

        removed_count
    }

    // TODO: pipelined, only city_name and count are transferred over the wire
    async fn pipelined_remove_people_in(city_name: &str, db: &BedyClient) -> usize {}
}
